# Site settings
title:                Matt Strimas-Mackey
tagline:              R Development for Conservation
description: >
    I am a conservation biologist researching tropical land use change and
    systematic conservation prioritization. I'm also interested in writing
    software to aid conservation decision making.
avatar:               https://avatars1.githubusercontent.com/u/7296482?v=3&s=460
baseurl:              ""
url:                  "http://mstrimas.github.io"

# Social details
author:
  name:               Matthew Strimas-Mackey
  email:              strimas@zoology.ubc.ca
  twitter:            StrimasMackey
  github:             mstrimas
  stackexchange:      26661

# Google Analytics
# google_analytics:

# Jekyll build settings
permalink:            /:categories/:title/
relative_permalinks:  true
markdown:             redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:          pygments
excerpt_separator:    <!-- more -->
sass:
  sass_dir:           _sass
  style:              :compressed
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
