---
layout: post
title: Noah Strycker's Birding Big Year (Part II)
published: true
excerpt: >
  Noah Strycker just broke the global big year record, seeing over 6,000 bird 
  species in 2015. I use ggplot to visualize his sightings over the course of the
  year.  
category: r
tags: r ggplot birding
---

```{r echo = F, include = F, eval = F}
setwd("_source/")
```

```{r packages}
library(readr)
library(dplyr)
library(magrittr)
library(sp)
```

```{r import}
var_names <- c("sub_id", "common_name", "species", "order", "count", 
               "adm_unit", "country", "location", "lat", "lng",
               "date", "time", "protocol", "duration", "all_obs",
               "dist_travelled", "n_obs", "sp_comments", "cl_comments")
sightings <- read_csv("data/big-year-2/strycker-all-sightings.csv", 
                      col_types = cols(count = col_character()),
                      col_names = var_names, skip = 1)
sightings$count[sightings$count == "X"] <- NA
sightings$common_name[sightings$common_name == "Taiwan Bamboo-Partidge"] <- 
  "Taiwan Bamboo-Partridge"
sightings <- sightings %>% 
  mutate(count = as.integer(count),
         not_species = grepl("(sp\\.$)|(hybrid)|(domestic)", common_name,
                             ignore.case = TRUE),
         undescribed = grepl("undescribed", common_name, ignore.case = TRUE),
         name = common_name) %>% 
  {
    .$name <- trimws(gsub("(\\(.*\\))|(\\[.*\\])", "", .$name))
    .$undescribed[.$name == "Peruvian Tyrannulet"] <- FALSE
    .$not_species <- (.$not_species | grepl("/", .$name))
    .
  }
glimpse(sightings)
spp <- filter(sightings, !not_species, !undescribed) %>% 
  {unique(.$name)}
length(spp)
bigyear <- readRDS("data/big-year/big-year.rds")
filter(sightings, !name %in% bigyear$species, !not_species, !undescribed) %>% 
  nrow
filter(bigyear, !species %in% spp) %>% 
  nrow
```

```{r save, echo=F, eval=F}
saveRDS(sightings, "data/big-year-2/sightings.rds")
sightings_wgs <- as.data.frame(sightings)
coordinates(sightings_wgs) <- ~ lng + lat
```